# fly.toml app configuration file generated for checkpoint-mood on 2026-03-16T18:27:52-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'checkpoint-mood'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true

[env]
  PORT = "8080"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[mounts]]
  source = "checkpoint_data"
  destination = "/data"
