"""Initial schema

Revision ID: 58a33c67ea61
Revises: 
Create Date: 2026-03-13 07:17:53.525718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a33c67ea61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'min_interval_hours')
    op.drop_column('settings', 'max_interval_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('max_interval_hours', sa.INTEGER(), nullable=True))
    op.add_column('settings', sa.Column('min_interval_hours', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
